# GET http://localhost:3000/student

# ###
# POST http://localhost:3000/student
# Content-Type: application/json

# {
#     "id": 5,
#     "name": "yoonhee",
#     "grade": "A",
#     "emailAddress" : "yoonhee@google.com"
#   }

# ### 
# PUT http://localhost:3000/student/1
# Content-Type: application/json

# {
#   "id": 1,
#   "name": "jiho",
#   "grade": "C",
#   "emailAddress": "jiiiihooo@google.com"
# },


GET http://localhost:3000/api/members

###
GET http://localhost:3000/api/members?team=engineering

###
GET http://localhost:3000/api/members?team=sales

###
GET http://localhost:3000/api/members?team=marketing

###
PUT http://localhost:3000/api/members/1
Content-Type: application/json

{
    "id": 1,
    "name": "Tooooooooooooom",
    "team": "engineering",
    "position": "Server Developer",
    "emailAddress": "alex@google.com",
    "phoneNumber": "010-xxxx-xxxx",
    "admissionDate": "2018/12/10",
    "birthday": "1994/11/08",
    "profileImage": "profile1.png"
}