GET http://localhost:3000/api/members

###
GET http://localhost:3000/api/members?team=sales

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
    "name": "Zoo",
    "team": "engineering",
    "position": "Andoid Developer",
    "emailAddress": "alex@google.com",
    "phoneNumber": "010-xxxx-xxxx",
    "admissionDate": "2018/11/10",
    "birthday": "1994/10/08",
    "profileImage": "profile11.png"
}

###
PUT http://localhost:3000/api/members/1
Content-Type: application/json

{
    "position": "IOS Developer"
}

###
DELETE http://localhost:3000/api/members/3